export const CONFIG = {
  startFrustration: 50,
  passiveGain: 8,
  anxietyGainPassive: 2,
  refuseCost: 0,
  chatCost: 3,
  hospitalCost: 10,
  startMoney: 500,
  hospitalCostMoney: 200,
  prices: {
    testkit: 50,
    prep: 100,
    alcohol: 30,
    gift: 150,
    energy: 20,
    medicine: 300,
  },
  rewards: {
    oral_condom: 6,
    oral_raw: 12,
    sex_condom: 10,
    sex_raw: 22,
  },
  stress: {
    oral_condom: 2,
    oral_raw: 15,
    sex_condom: 5,
    sex_raw: 30,
  },
};

export const AVATARS = ['👩', '👱‍♀️', '👧', '👩‍🦰', '👩‍🦱', '👩‍🦳', '💃', '🧚‍♀️', '👸', '👯‍♀️', '🧝‍♀️', '🧛‍♀️', '🧜‍♀️', '🦹‍♀️', '👩‍🎤', '👩‍🎓', '👩‍🏫', '👩‍⚖️'];

export const DISEASES: Record<string, { name: string; riskType: string; desc: string; transmission: string }> = {
  HIV: { name: "艾滋病 (HIV)", riskType: "fluid", desc: "免疫崩溃，不可逆转。", transmission: "体液传播" },
  SYPHILIS: { name: "梅毒", riskType: "contact", desc: "全身红斑，侵蚀神经。", transmission: "接触传播" },
  HERPES: { name: "疱疹", riskType: "skin", desc: "终身携带，反复剧痛。", transmission: "皮肤接触" },
  HPV: { name: "尖锐湿疣", riskType: "contact", desc: "菜花突起，极难根治。", transmission: "接触传播" },
  GONORRHEA: { name: "淋病", riskType: "fluid_mucous", desc: "流脓刺痛。", transmission: "体液粘膜" },
  CRABS: { name: "阴虱", riskType: "skin_hair", desc: "剧烈瘙痒。", transmission: "密切接触" },
  CHLAMYDIA: { name: "衣原体感染", riskType: "fluid_mucous", desc: "尿道刺痛，易致不孕不育。", transmission: "体液粘膜" },
  HEPATITIS_B: { name: "乙肝", riskType: "fluid", desc: "肝脏损伤，可能发展为肝癌。", transmission: "体液传播" },
};

export const FLIRT_LINES = [
  "哥哥，今晚有空吗？",
  "最近好无聊，想找个人陪陪我...",
  "刚洗完澡，头发还没干呢。",
  "大叔，带带妹妹呗~",
  "一个人喝酒好没意思，你来吗？",
  "我只找走心的，不约（主页却很暴露）。",
  "今晚室友不在家哦。",
  "失恋了，想借个肩膀靠一下。",
  "周末好无聊，想出去兜风~",
  "你长得好像我前男友...",
  "别害羞，靠近点。",
  "我的忍耐是有限度的。",
  "我这人说话比较直，你别介意。",
  "你平时周末都喜欢干嘛？",
  "我其实有点社恐...",
  "你懂的，成年人的世界哪有容易二字。",
  "我这个人很慢热的。",
  "你相信一见钟情吗？",
  "我平时很少用这个软件的。",
  "你看起来很会照顾人。",
  "今晚月色真美。",
  "要不要来我家看猫？会后空翻那种。",
  "我有点醉了，你能送我回家吗？",
  "一个人喝酒好没意思，你来吗？",
  "最近压力好大，想找个地方放松一下。",
  "你长得很像我前男友。",
  "今晚不想回去了...",
  "我只和有感觉的人做。",
  "你平时都喜欢玩什么呀？",
  "我不太会喝酒，你可别灌我。",
  "你觉得我今天穿的这身好看吗？",
  "我喜欢主动一点的男生。",
  "你身上有一种很特别的味道。",
  "我平时其实很乖的，但今天想放纵一下。",
  "你看起来很有经验的样子。",
  "我们是不是在哪里见过？",
  "你相信一见钟情吗？",
  "我有点冷，你能抱抱我吗？",
  "你是我见过最特别的人。",
  "我不想一个人睡。",
  "你愿意听听我的故事吗？",
  "我喜欢你的眼睛，里面有星星。",
  "你让我有一种很安心的感觉。",
  "我想和你一起看明天的日出。",
  "你猜我现在在想什么？",
  "我觉得我们之间有一种奇妙的化学反应。"
];

export interface Tag {
  text: string;
  color: string;
  risk?: Record<string, number>;
  safeChance?: number;
  constraint?: string;
  clue: string;
  hiddenChance: number;
  safetyBonus?: boolean;
}

export const ALL_TAGS: Tag[] = [
  { text: "清纯女大", color: "bg-pink-600", risk: { HPV: 0.05 }, constraint: "condom_only", clue: "【身份】看起来很乖巧，学生气很重。", hiddenChance: 0.3 },
  { text: "夜店常客", color: "bg-purple-600", risk: { HIV: 0.05, SYPHILIS: 0.1, HPV: 0.2, GONORRHEA: 0.15 }, clue: "【生活】朋友圈全是蹦迪和喝酒的照片。", hiddenChance: 0.6 },
  { text: "离异少妇", color: "bg-rose-700", risk: { HPV: 0.1, SYPHILIS: 0.05 }, clue: "【身份】气质成熟，眼神里透着故事。", hiddenChance: 0.4 },
  { text: "福利姬", color: "bg-fuchsia-600", risk: { HIV: 0.02, SYPHILIS: 0.08, GONORRHEA: 0.1 }, constraint: "condom_only", clue: "【身份】主页有很多大尺度的二次元擦边照。", hiddenChance: 0.5 },
  { text: "绿茶妹妹", color: "bg-emerald-600", risk: { HPV: 0.08 }, clue: "【性格】说话嗲嗲的，总是暗示你给她买东西。", hiddenChance: 0.4 },
  { text: "海后", color: "bg-blue-600", risk: { HIV: 0.08, SYPHILIS: 0.15, GONORRHEA: 0.2, HPV: 0.3 }, clue: "【性格】极其熟练，似乎同时在和很多人聊天。", hiddenChance: 0.7 },
  { text: "刚失恋", color: "bg-slate-500", risk: { GONORRHEA: 0.05 }, constraint: "oral_only", clue: "【状态】眼眶红红的，一直在骂前男友。", hiddenChance: 0.2 },
  { text: "寻求刺激", color: "bg-red-600", risk: { HIV: 0.1, SYPHILIS: 0.1, GONORRHEA: 0.1 }, clue: "【状态】主动提出去没人的地方，暗示可以无套。", hiddenChance: 0.5 },
  { text: "保守传统", color: "bg-teal-600", risk: { HPV: 0.02 }, constraint: "condom_only", clue: "【性格】穿着很严实，一直强调自己不是随便的人。", hiddenChance: 0.2 },
  { text: "生理期", color: "bg-red-900", risk: { HIV: 0.2 }, constraint: "oral_only", clue: "【限制】捂着肚子，说今天身体不太舒服。", hiddenChance: 0.5 },
  { text: "职业工作者", color: "bg-yellow-600", risk: { HIV: 0.15, SYPHILIS: 0.2, GONORRHEA: 0.3, HPV: 0.4 }, constraint: "condom_only", clue: "【身份】明码标价，动作非常专业且机械。", hiddenChance: 0.8 },
  { text: "母胎单身", color: "bg-sky-500", risk: {}, constraint: "no_sex", clue: "【状态】非常紧张，连牵手都会脸红。", hiddenChance: 0.3 },
  { text: "护士姐姐", color: "bg-cyan-600", risk: { HPV: 0.05 }, constraint: "condom_only", clue: "【身份】懂得很多医学知识，随身带着消毒湿巾。", hiddenChance: 0.4 },
  { text: "健身教练", color: "bg-orange-600", risk: { GONORRHEA: 0.08 }, clue: "【身份】身材极好，马甲线清晰可见。", hiddenChance: 0.3 },
  { text: "定期体检", color: "bg-emerald-500", risk: {}, safeChance: 0.9, clue: "【健康】主动出示了最近的体检报告。", hiddenChance: 0.6 },
  { text: "身上有红斑", color: "bg-red-800", risk: { SYPHILIS: 0.8, HIV: 0.2 }, clue: "【危险】脖子和手臂上有奇怪的暗红色斑点。", hiddenChance: 0.9 },
  { text: "私生活混乱", color: "bg-purple-800", risk: { HIV: 0.3, SYPHILIS: 0.4, GONORRHEA: 0.5, HPV: 0.6 }, clue: "【危险】无意间看到她手机里有十几个不同的约会软件。", hiddenChance: 0.8 },
  { text: "手掌/脚底有红斑", color: "bg-red-700", risk: { SYPHILIS: 0.95 }, clue: "如果你看到这个，跑！这是梅毒二期的典型铁证。", hiddenChance: 0.8 },
  { text: "私处长了个硬硬的红疮", color: "bg-red-700", risk: { SYPHILIS: 0.98 }, clue: "这就叫『硬下疳』。不痛不痒，但那是梅毒一期。", hiddenChance: 0.9 },
  { text: "嘴角长了一簇水泡", color: "bg-red-700", risk: { HERPES: 0.9 }, clue: "疱疹正在发作，水泡液里全是病毒，碰一下就中招。", hiddenChance: 0.9 },
  { text: "内裤上有黄色分泌物", color: "bg-red-600", risk: { GONORRHEA: 0.9 }, clue: "典型的淋病症状。真的很脏。", hiddenChance: 0.5 },
  { text: "后面长了菜花状的小肉粒", color: "bg-red-800", risk: { HPV: 0.95, SYPHILIS: 0.4 }, clue: "尖锐湿疣。如果不切除会越长越大，像菜花一样。", hiddenChance: 0.9 },
  { text: "毛发根部有会动的黑痂", color: "bg-red-800", risk: { CRABS: 0.95 }, clue: "那不是脏东西，是阴虱和它的卵。它会爬到你身上。", hiddenChance: 0.7 },
  { text: "张嘴看到舌头白得像长霉", color: "bg-red-800", risk: { HIV: 0.6, SYPHILIS: 0.3 }, clue: "鹅口疮。成年人很少得，除非免疫系统崩了（比如艾滋病）。", hiddenChance: 0.5 },
  { text: "身上有紫红色的斑块", color: "bg-purple-800", risk: { HIV: 0.7 }, clue: "疑似卡波西肉瘤，艾滋病发病期的标志之一。", hiddenChance: 0.8 },
  { text: "头发像被虫蛀了一样稀疏", color: "bg-purple-700", risk: { SYPHILIS: 0.6 }, clue: "梅毒性脱发，通常是虫蚀状的，不是普通的秃顶。", hiddenChance: 0.3 },
  { text: "脖子/腋下摸起来有肿块", color: "bg-purple-700", risk: { HIV: 0.4, SYPHILIS: 0.4 }, clue: "全身淋巴结肿大，身体正在对抗病毒。", hiddenChance: 0.7 },
  { text: "躯干长满了不痒的红疹", color: "bg-purple-700", risk: { SYPHILIS: 0.5, HIV: 0.2 }, clue: "梅毒疹通常不痛不痒，很容易被误认为是过敏。", hiddenChance: 0.8 },
  { text: "舌头侧面有白色毛状物", color: "bg-purple-800", risk: { HIV: 0.8 }, clue: "毛状白斑，免疫系统严重受损的信号。", hiddenChance: 0.6 },
  { text: "房间里有刺鼻的化学味", color: "bg-rose-900", risk: { HIV: 0.4, SYPHILIS: 0.3 }, clue: "RUSH(亚硝酸盐)的味道。玩这么大，通常伴随无套群交。", hiddenChance: 0.5 },
  { text: "提议去公园/公厕解决", color: "bg-rose-900", risk: { SYPHILIS: 0.4, HIV: 0.3 }, clue: "野外游击队(Cruising)。环境极脏，且通常有多性伴。", hiddenChance: 0 },
  { text: "刚参加完多人派对", color: "bg-rose-900", risk: { HIV: 0.5, SYPHILIS: 0.5, GONORRHEA: 0.5 }, clue: "交叉感染的温床。你永远不知道上一个人是谁。", hiddenChance: 0.6 },
  { text: "也是刚约完上一个人", color: "bg-rose-800", risk: { GONORRHEA: 0.4, SYPHILIS: 0.3 }, clue: "无缝衔接。这种频率，中招是迟早的事。", hiddenChance: 0.5 },
  { text: "说『我就蹭蹭不进去』", color: "bg-rose-700", risk: { HERPES: 0.3, HPV: 0.3 }, clue: "著名的渣女谎言。而且蹭蹭也能传染皮肤病。", hiddenChance: 0 },
  { text: "说『如果你是干净的就能无套』", color: "bg-rose-900", risk: { HIV: 0.2 }, clue: "典型的渣女话术PUA。这就是想骗你无套。", hiddenChance: 0 },
  { text: "脖子上有新鲜的吻痕", color: "bg-rose-800", risk: { HIV: 0.1, SYPHILIS: 0.1 }, clue: "私生活混乱的直接证据，可能昨晚还在别人床上。", hiddenChance: 0.3 },
  { text: "App显示24小时在线", color: "bg-purple-800", risk: { HIV: 0.15, SYPHILIS: 0.15 }, clue: "住在软件上的极度活跃用户，常在河边走，哪有不湿鞋。", hiddenChance: 0 },
  { text: "极度消瘦/脸颊凹陷", color: "bg-purple-700", risk: { HIV: 0.35 }, clue: "可能是艾滋病消耗期，也可能是吸毒吸的。", hiddenChance: 0.2 },
  { text: "一直在咳嗽/盗汗", color: "bg-purple-700", risk: { HIV: 0.2 }, clue: "免疫力低下的表现，需警惕。", hiddenChance: 0.3 },
  { text: "坚持不开灯/只开夜灯", color: "bg-purple-900", risk: { SYPHILIS: 0.4, HERPES: 0.4, HPV: 0.4 }, clue: "最经典的伪装。黑暗是为了掩饰身上的溃疡或皮疹。", hiddenChance: 0 },
  { text: "大热天非要穿高领", color: "bg-purple-800", risk: { SYPHILIS: 0.5, HIV: 0.2 }, clue: "欲盖弥彰。可能在遮挡吻痕，也可能是皮疹或淋巴结肿大。", hiddenChance: 0 },
  { text: "包里自备各种安全套", color: "bg-sky-700", risk: {}, safetyBonus: true, constraint: "condom_only", clue: "安全意识极强，大概率对自己和他人都负责。", hiddenChance: 0.3 },
  { text: "明确拒绝无套提议", color: "bg-sky-700", risk: {}, safetyBonus: true, constraint: "condom_only", clue: "有原则的人通常比较安全。", hiddenChance: 0 },
  { text: "对乳胶/橡胶过敏", color: "bg-rose-800", risk: {}, constraint: "no_condom", clue: "【限制】生理原因无法戴普通套。", hiddenChance: 0.4 },
  { text: "特别讨厌橡胶味", color: "bg-rose-800", risk: { HIV: 0.15 }, constraint: "no_condom", clue: "【限制】心理抵触戴套。如果你坚持，只能离开。", hiddenChance: 0.2 },
  { text: "嘴里有溃疡/起泡", color: "bg-red-800", risk: { HIV: 0.2, SYPHILIS: 0.3 }, constraint: "no_oral", clue: "【限制】嘴疼无法口交，且有体液传播风险。", hiddenChance: 0.6 },
  { text: "比较保守/只敢边缘", color: "bg-sky-800", risk: {}, constraint: "oral_only", clue: "【限制】胆子小，拒绝插入，只接受手口。", hiddenChance: 0 },
  { text: "室友就在隔壁", color: "bg-slate-600", risk: {}, constraint: "oral_only", clue: "【限制】不敢发出声音，只能悄悄来。", hiddenChance: 0.1 },
  { text: "情绪稳定", color: "bg-emerald-700", risk: {}, safetyBonus: true, clue: "【性格】无论发生什么都很淡定，让人安心。", hiddenChance: 0.2 },
  { text: "PUA大师", color: "bg-rose-900", risk: { HIV: 0.1, SYPHILIS: 0.2 }, constraint: "no_condom", clue: "【危险】总是试图打压你的自信心。", hiddenChance: 0.7 },
  { text: "画大饼", color: "bg-amber-600", risk: { GONORRHEA: 0.1 }, clue: "【性格】说得天花乱坠，但从不兑现。", hiddenChance: 0.5 },
  { text: "妈宝", color: "bg-sky-600", risk: {}, constraint: "condom_only", clue: "【性格】三句话离不开“我妈说”。", hiddenChance: 0.4 },
  { text: "隐形富豪", color: "bg-yellow-500", risk: { HPV: 0.1 }, clue: "【身份】穿着低调，但用的东西都很贵。", hiddenChance: 0.8 },
  { text: "极度自恋", color: "bg-fuchsia-500", risk: { HPV: 0.1 }, clue: "【性格】只关心自己，从不听你说话。", hiddenChance: 0.5 },
  { text: "情绪不稳定", color: "bg-red-500", risk: { GONORRHEA: 0.1 }, clue: "【性格】上一秒还在笑，下一秒就发脾气。", hiddenChance: 0.6 },
  { text: "有洁癖", color: "bg-teal-500", risk: {}, safeChance: 0.8, constraint: "condom_only", clue: "【习惯】随身带酒精喷雾，碰什么都要消毒。", hiddenChance: 0.4 },
  { text: "喜欢户外", color: "bg-green-600", risk: { CRABS: 0.1 }, clue: "【爱好】经常去野外露营，皮肤晒得很黑。", hiddenChance: 0.5 },
  { text: "纹身爱好者", color: "bg-slate-700", risk: { HIV: 0.05, SYPHILIS: 0.05 }, clue: "【外观】身上有很多纹身，有些看起来很新。", hiddenChance: 0.6 },
  { text: "经常熬夜", color: "bg-gray-600", risk: { HERPES: 0.2 }, clue: "【习惯】黑眼圈很重，看起来很疲惫。", hiddenChance: 0.4 },
  { text: "喜欢极限运动", color: "bg-orange-700", risk: { HERPES: 0.1 }, clue: "【爱好】追求刺激，身上常有淤青。", hiddenChance: 0.5 },
  { text: "素食主义者", color: "bg-green-500", risk: {}, safeChance: 0.5, clue: "【习惯】饮食清淡，看起来很健康。", hiddenChance: 0.3 },
  { text: "有宠物", color: "bg-yellow-700", risk: { CRABS: 0.05 }, clue: "【生活】身上常有猫狗的毛发。", hiddenChance: 0.2 },
  { text: "刚分手", color: "bg-blue-600", risk: { GONORRHEA: 0.2, CHLAMYDIA: 0.2 }, clue: "【状态】情绪低落，急需安慰，可能处于报复性放纵期。", hiddenChance: 0.6 },
  { text: "异地恋", color: "bg-purple-600", risk: { SYPHILIS: 0.1, HPV: 0.1 }, clue: "【状态】长期见不到伴侣，偷偷出来寻找刺激。", hiddenChance: 0.8 },
  { text: "喜欢去夜店", color: "bg-fuchsia-700", risk: { HIV: 0.1, SYPHILIS: 0.2, GONORRHEA: 0.3 }, clue: "【爱好】夜生活丰富，接触的人员复杂。", hiddenChance: 0.5 },
  { text: "有轻微洁癖", color: "bg-teal-400", risk: {}, safeChance: 0.7, constraint: "condom_only", clue: "【习惯】要求洗澡后才能碰，对卫生要求高。", hiddenChance: 0.3 },
  { text: "喜欢刺激", color: "bg-rose-600", risk: { HIV: 0.2, SYPHILIS: 0.2 }, constraint: "no_condom", clue: "【性格】觉得戴套不舒服，总是试图说服你无套。", hiddenChance: 0.7 },
  { text: "极度缺乏安全感", color: "bg-indigo-500", risk: {}, constraint: "condom_only", clue: "【性格】总是担心得病，要求必须做好防护。", hiddenChance: 0.4 },
];

export const RANDOM_EVENTS = [
  { id: 'ex', title: '前女友的问候', desc: '深夜收到了前女友的短信，回忆涌上心头...', effect: { frustration: 15, anxiety: 10, money: 0 } },
  { id: 'video', title: '深夜男科科普', desc: '刷短视频看到了一篇关于梅毒的硬核科普，越看越害怕。', effect: { frustration: 0, anxiety: 20, money: 0 } },
  { id: 'bonus', title: '意外之财', desc: '在旧外套口袋里翻出了两百块钱！', effect: { frustration: 0, anxiety: 0, money: 200 } },
  { id: 'horny', title: '欲火焚身', desc: '看了几部小电影，你感到异常的空虚和饥渴。', effect: { frustration: 20, anxiety: 0, money: 0 } },
  { id: 'peace', title: '贤者时间', desc: '突然看破红尘，觉得女人只会影响你拔剑的速度。', effect: { frustration: -15, anxiety: -10, money: 0 } },
  { id: 'scam', title: '遭遇仙人跳', desc: '刚进房间就冲进来几个大汉，被迫破财消灾。', effect: { frustration: 0, anxiety: 30, money: -300 } },
  { id: 'bro', title: '兄弟局', desc: '兄弟叫你去喝酒撸串，心情大好。', effect: { frustration: -10, anxiety: -20, money: -100 } },
  { id: 'scam2', title: '杀猪盘', desc: '被网上的“理财大师”骗了一笔钱。', effect: { frustration: 0, anxiety: 20, money: -200 } },
  { id: 'sick', title: '感冒发烧', desc: '身体不适，不仅花了钱看病，还耽误了时间。', effect: { frustration: 10, anxiety: 10, money: -50 } },
  { id: 'lottery', title: '刮刮乐中奖', desc: '随手买了一张刮刮乐，竟然中奖了！', effect: { frustration: -5, anxiety: -5, money: 300 } },
  { id: 'gym', title: '健身房办卡', desc: '被教练忽悠办了年卡，钱包大出血，但感觉自己变强了。', effect: { frustration: -20, anxiety: -10, money: -500 } },
  { id: 'pet', title: '路边撸猫', desc: '遇到一只很亲人的流浪猫，心情被治愈了。', effect: { frustration: -10, anxiety: -15, money: 0 } },
  { id: 'game', title: '游戏连败', desc: '打排位遭遇十连败，气得想砸手机。', effect: { frustration: 25, anxiety: 15, money: 0 } },
  { id: 'lost', title: '丢了钱包', desc: '在地铁上钱包被偷了，身份证银行卡全得补办。', effect: { frustration: 10, anxiety: 30, money: -200 } },
  { id: 'rain', title: '突降暴雨', desc: '没带伞被淋成了落汤鸡，心情糟糕透顶。', effect: { frustration: 15, anxiety: 5, money: 0 } },
  { id: 'food', title: '吃到神仙美食', desc: '偶然发现一家超好吃的苍蝇馆子，幸福感爆棚。', effect: { frustration: -15, anxiety: -5, money: -30 } },
  { id: 'scam3', title: '酒托', desc: '约出来的女生带你去了一家不知名酒吧，结账时傻眼了。', effect: { frustration: 20, anxiety: 10, money: -800 } },
  { id: 'ghost', title: '被放鸽子', desc: '在寒风中等了两个小时，对方把你拉黑了。', effect: { frustration: 30, anxiety: 10, money: 0 } },
  { id: 'gift', title: '意外礼物', desc: '收到了暗恋对象送的小礼物，开心了一整天。', effect: { frustration: -25, anxiety: -15, money: 0 } },
  { id: 'work', title: '加班', desc: '老板突然让你周末加班，约会泡汤了。', effect: { frustration: 20, anxiety: 15, money: 100 } },
  { id: 'gym_injury', title: '健身受伤', desc: '硬拉闪了腰，不仅要花钱看医生，还不能剧烈运动。', effect: { frustration: 30, anxiety: 10, money: -200 } },
  { id: 'stock_crash', title: '股票大跌', desc: '买的基金一片绿，辛辛苦苦攒的钱没了一半。', effect: { frustration: 10, anxiety: 40, money: -1000 } },
  { id: 'old_friend', title: '老友重逢', desc: '在街上偶遇了多年不见的老同学，聊得很开心。', effect: { frustration: -15, anxiety: -20, money: -50 } },
  { id: 'phone_broken', title: '手机碎屏', desc: '手机掉地上屏幕碎了，换个屏幕好贵。', effect: { frustration: 20, anxiety: 15, money: -400 } },
  { id: 'good_sleep', title: '深度睡眠', desc: '昨晚睡得特别好，感觉整个人都焕然一新。', effect: { frustration: -20, anxiety: -20, money: 0 } },
  { id: 'bad_haircut', title: '理发翻车', desc: '理发师完全没听懂你的要求，剪了个极丑的发型。', effect: { frustration: 25, anxiety: 30, money: -50 } },
  { id: 'found_money', title: '捡到钱', desc: '在路上捡到了一百块钱，运气真好！', effect: { frustration: -5, anxiety: -5, money: 100 } },
  { id: 'neighbor_noise', title: '邻居装修', desc: '楼上邻居大清早开始电钻，吵得你头痛欲裂。', effect: { frustration: 30, anxiety: 20, money: 0 } },
  { id: 'favorite_song', title: '听到喜欢的歌', desc: '在便利店听到了很久没听的爱歌，心情大好。', effect: { frustration: -10, anxiety: -10, money: 0 } },
  { id: 'traffic_jam', title: '严重堵车', desc: '被堵在路上两个小时，错过了重要的约会。', effect: { frustration: 35, anxiety: 25, money: -30 } },
  { id: 'std_scare', title: '虚惊一场', desc: '发现身上长了个红点，吓得半死，去医院检查发现是蚊子咬的。', effect: { frustration: 0, anxiety: -30, money: -50 } },
  { id: 'drunk_text', title: '酒后乱发消息', desc: '喝醉了给前任发了一堆消息，第二天醒来想死的心都有了。', effect: { frustration: 40, anxiety: 30, money: 0 } },
  { id: 'dating_app_ban', title: '账号被封', desc: '因为被人举报，你的交友软件账号被永久封禁了。', effect: { frustration: 50, anxiety: 20, money: 0 } },
];
